"""Build the v12 board: figures -> inline SVG -> poster.html -> PDF + PNG preview, then gates.

usage: python poster/build_v12.py [--no-figures]
needs: weasyprint, pypdfium2, matplotlib, qrcode (see research/repro/README.md)

Gates (each fails loudly; an unknown result is a failure, never a skip):
  1. exactly one PDF page, 841 x 1189 mm
  2. no content box ends below the footer's top edge, and the footer sits inside the page
  3. prose: no em or en dashes in running text (ranges use a hyphen-free 'to' or the
     typographic range sign inside numbers only), no banned tell words
  4. every figure/QR referenced exists and every QR payload matches its .txt
"""
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "src" / "poster.v12.html"
OUT_HTML = HERE / "poster.html"
PDF = HERE / "emem-poster-A0.pdf"
PNG = HERE / "emem-poster-preview.png"


def run_figures():
    subprocess.run([sys.executable, str(HERE.parent / "research" / "repro" / "v11" / "mutation_suite.py")], check=True,
                   stdout=subprocess.DEVNULL)
    subprocess.run([sys.executable, str(HERE / "make_figures_v12.py")], check=True)


def inline(html: str) -> str:
    def rep(m):
        p = HERE / m.group(1)
        if not p.exists():
            sys.exit(f"GATE FAIL: missing inline asset {p}")
        svg = p.read_text()
        svg = re.sub(r"<\?xml[^>]*\?>", "", svg).strip()
        return svg
    return re.sub(r"<!--inline:([^>]+?)-->", rep, html)


def prose_gate(html: str):
    body = re.sub(r"(?s)<style.*?</style>|<svg.*?</svg>|<!--.*?-->", "", html)
    text = re.sub(r"<[^>]+>", " ", body)
    bad = []
    for m in re.finditer(r"—", text):
        bad.append("em dash: " + text[max(0, m.start() - 40):m.end() + 40].strip())
    for m in re.finditer(r"–", text):
        a, b = text[m.start() - 1:m.start()], text[m.end():m.end() + 1]
        if not (a.isdigit() and (b.isdigit() or b == "")) and not (a.isalnum() and b.isalnum() and a.isupper()):
            bad.append("en dash outside a numeric range: " + text[max(0, m.start() - 30):m.end() + 30].strip())
    tells = ["robust", "seamless", "leverage", "cutting-edge", "game-chang", "revolutioni", "unlock", "delve",
             "paradigm", "groundbreaking", "state-of-the-art", "empower", "synergy"]
    low = text.lower()
    bad += [f"tell word: {w}" for w in tells if w in low]
    if bad:
        sys.exit("GATE FAIL (prose):\n  " + "\n  ".join(bad))
    return len(text.split())


def qr_gate():
    import qrcode  # noqa: F401  (payloads are regenerated by make_figures; here we check the files agree)
    txts = sorted((HERE / "fig" / "v12").glob("qr_*.txt"))
    if len(txts) < 2:
        sys.exit("GATE FAIL: expected two QR payload files in fig/v12")
    for txt in txts:
        svg = txt.with_suffix(".svg")
        if not svg.exists():
            sys.exit(f"GATE FAIL: {svg} missing for {txt}")


def layout_gate(html: str):
    import weasyprint
    doc = weasyprint.HTML(string=html, base_url=str(HERE)).render()
    if len(doc.pages) != 1:
        sys.exit(f"GATE FAIL: {len(doc.pages)} pages, expected 1")
    pg = doc.pages[0]
    w_mm, h_mm = pg.width * 25.4 / 96, pg.height * 25.4 / 96
    if abs(w_mm - 841) > 0.5 or abs(h_mm - 1189) > 0.5:
        sys.exit(f"GATE FAIL: page {w_mm:.1f} x {h_mm:.1f} mm")
    foot_top, main_bottom = None, None

    def walk(box):
        nonlocal foot_top, main_bottom
        tag = getattr(box, "element_tag", None)
        if tag == "footer" and foot_top is None:
            foot_top = box.position_y
        if tag == "main":
            main_bottom = box.position_y + box.margin_height()
        for ch in getattr(box, "children", []) or []:
            walk(ch)
    walk(pg._page_box)
    if foot_top is None or main_bottom is None:
        sys.exit("GATE FAIL: could not locate <main> or <footer> boxes (layout unknown)")
    gap_mm = (foot_top - main_bottom) * 25.4 / 96
    print(f"layout: main ends {main_bottom * 25.4 / 96:.1f} mm, footer starts {foot_top * 25.4 / 96:.1f} mm, gap {gap_mm:.1f} mm")
    if gap_mm < 2.0:
        sys.exit(f"GATE FAIL: content overruns the footer by {-gap_mm:.1f} mm (need >= 2 mm clearance)")
    return doc, gap_mm


def main():
    if "--no-figures" not in sys.argv:
        run_figures()
    html = inline(SRC.read_text())
    words = prose_gate(html)
    qr_gate()
    OUT_HTML.write_text(html)
    doc, gap = layout_gate(html)
    doc.write_pdf(str(PDF))
    import pypdfium2 as pdfium
    pdf = pdfium.PdfDocument(str(PDF))
    if len(pdf) != 1:
        sys.exit("GATE FAIL: written PDF is not one page")
    img = pdf[0].render(scale=3179 / pdf[0].get_width()).to_pil().convert("RGB")
    img.save(PNG, optimize=True)
    print(f"ok: {PDF.name} ({PDF.stat().st_size / 1e6:.2f} MB), {PNG.name} {img.size}, {words} words, clearance {gap:.1f} mm")


if __name__ == "__main__":
    main()
