# Verbatim briefs given to the two audit sub-agents on 30 Sep 2026 (context, tasks, output schemas).
# Reuse them to re-run the audits at a later emem commit. Outputs: research/audit_v11/.

ctx = """Context: Avijeet Singh (founder, Vortx AI) and Jaya Kumari present the poster 'EMEM: A Content-Addressed, Verifiable Earth-Memory Protocol for AI Agents over Foundation-Model Embeddings' at the ESA/BIFOLD Agentic AI for Earth Observation workshop, Berlin, Poster Session 1, 19 Oct 2026 17:00-18:30 (23 posters; neighbours include GeoGuard guardrails, domain-grounded evaluation of EO agents, a trustworthy NASA discovery agent, Earthward traceable HITL workflows). Paper DOI 10.5281/zenodo.20706893. The current poster (v10) lives in github.com/Vortx-AI/esa_poster (main at 50bb8bf; poster/poster.html; research/ holds a claims ledger, invention register, defects list, repro scripts, v10/algorithms.md). The emem reference implementation is github.com/Vortx-AI/emem (Rust, Apache-2.0; HEAD e226f8b on 30 Sep 2026; live responder at https://emem.dev, MCP at https://emem.dev/mcp, REST at https://emem.dev/v1). The v10 poster is accurate but reads like a forensic audit / work log: it indexes only a slice of what emem is (one NDVI fact, pixel bug, handoff trials) and gives lots of space to self-refutation. We are redesigning it into an invention-grade research poster. Every claim must stay true to code and measured evidence. Clone repos with plain `git clone https://github.com/...` (HTTPS works). Do NOT push to any git remote, do NOT publish/sign/write anything to emem.dev (no POST that creates memories/notes); read-only GET requests to emem.dev are fine but keep them few (note: emem read tools may sign new records, so prefer static endpoints like /.well-known/emem.json, /v1/capabilities, /v1/log/witnesses, /v1/tools.json, /openapi.json, /v1/algorithms?limit=1)."""

inventory_task = """Build a complete, evidence-backed CAPABILITY INDEX of emem as it exists at github.com/Vortx-AI/emem HEAD (record the commit you read). Goal: the poster currently shows only ~1/5 of what emem is; we need the whole invention mapped so the redesign can show it truthfully.
Cover at minimum (verify each in code; say 'not found' if absent):
1. Data model: the fact tuple fields, canonical CBOR profile, fact_cid construction, cell64 grid (resolution, encoding), tslot per source, bi-temporal model (valid time vs signed_at / transaction time, as-of recall rule).
2. Every token family and its binding strength: emem:fact, raster, cube, rasterset, tree (pointer), bundle (memb/memt), entity, any others (e.g. track, note, world). For each: what bytes it hashes, whether it is recomputable, resolve endpoint.
3. Trust plane: batch attestation, Merkle root, RFC 6962-style transparency log (tree size, witnesses/co-signers), receipt preimage, key publication (did:web/JWKS/DNS), signed absence, verification classes (e.g. recomputable / re-readable / attester_only) if such a classification exists in code or docs.
4. Agent plane: agents signing their own notes (by_attester namespaces), hash-chained tracks, inbox/correspondence, pointer.v1 (hash files in place), derive with ulp tolerance, draft/claim checker (verify-before-publish), contradiction detection, predictions, entity/alias, A2A agent card, federation/witness/replication, device/OS-trace gate, worlds (gaussian splats) — whatever exists.
5. Algorithm registry: count of registered algorithms and families (spectral indices, crop, forest, water, terrain, etc.), how algorithms are addressed/versioned (algorithms_cid).
6. Data sources: count of declared sources and bands, main catalogues (Sentinel-2 via Earth Search / Planetary Computer, Copernicus DEM, weather, forest products, TESSERA embeddings...).
7. Distribution surface: MCP tool count (core vs total), REST path count, A2A, SDKs (PyPI ememdev, npm @vortxai/emem), framework adapters, Claude skills/plugins in the repo, docker image; usage stats if published in repo.
8. Status of foundation-model encoders (which were removed, which remain, what 'frozen' means) and exactly what still resolves for vectors signed before removal.
9. Anything genuinely distinctive vs STAC/COG/openEO/Earth Engine/vector-DB agent memory that the poster should claim, stated precisely.
For every item give: short description, file path(s) with line numbers or doc section, status (shipped+live / shipped-not-live / docs-only / roadmap), and any number with its source. Do a few read-only GETs on emem.dev to get live counts (tools, algorithms, sources, log size) and record timestamps.
Deliverables (save as artifacts): emem_capability_index.md (human readable, organised as the 9 sections above plus a final 'Top 10 invention claims, strongest first' list with evidence pointers) and emem_capability_index.json (same content, machine-readable)."""

claims_task = """Audit the poster repo github.com/Vortx-AI/esa_poster (main, commit 50bb8bf or later) to produce the evidence base for an invention-grade redesign.
Read: poster/poster.html (v10), poster/README.md, research/README.md, research/RESEARCH_STATE.md, all of research/should_do/*.md (esp. 04_VERIFIED_CLAIMS_LEDGER, 05_EVIDENCE_AND_NUMBERS, 09_INVENTION_REGISTER, 11, 12, 14_REAL_GAP_STUDY), all of research/do_not_use/*.md, research/repro/README.md, research/repro/v10/algorithms.md, research/repro/data/v8/results.json, research/repro/data/v9/rawband/results.md.
Produce:
A. CLAIM TABLE: every quantitative or mechanism claim printed on the v10 poster, with its value, the source file that supports it, whether the source actually supports it exactly (flag mismatches, rounding problems, stale numbers, internal contradictions between panels), and its evidence class (measured n=?, pre-registered?, exploratory, code-read, docs-only).
B. STRONGEST RESULTS: the 10 results that best support emem as an invention (not as an audit), each with exact numbers, n, p-values/intervals as recorded, and the one-line caveat that must travel with it.
C. OBJECTIONS AND ANSWERS: the 10-12 hardest objections an ESA/BIFOLD reviewer or a neighbouring poster author (guardrails, evaluation, traceability) would raise (e.g. 'a signature doesn't make a value true', 'tokens cost more LLM tokens than the value', 'BM25 ties you', 'you retired your foundation-model encoders but the title says over Foundation-Model Embeddings', 'your own reader wrote 162/200 wrong-pixel records', 'geo.qa co-signer is also Vortx', 'single responder, no federation', 'n is small, one host', 'why not STAC + checksums / C2PA / W3C PROV / IPFS'). For each: the strongest honest answer grounded in the repo's evidence, and whether the answer is 'rebuttal', 'reframe', or 'concede + scope'.
D. REFUTATIONS POLICY: a short, reasoned recommendation on how much self-refutation belongs on a workshop poster vs in the repo/handout, citing the specific v10 panels (\u00a79 'emem retired its encoders', \u00a710 'where emem lost', \u00a713 'what is not established', defects list) and what to do with each (keep / reframe / move to handout).
E. LIST of every emem token string, CID, hash and URL printed on v10 (verbatim, copied programmatically from poster.html), so the redesign reuses them exactly.
Deliverables (save as artifacts): poster_evidence_audit.md (sections A-E) and poster_evidence_audit.json (A, B, C, E machine-readable)."""

schema_inv = {"type":"object","properties":{"emem_commit":{"type":"string"},"summary":{"type":"string"},"top_claims":{"type":"array","items":{"type":"object","properties":{"claim":{"type":"string"},"evidence":{"type":"string"},"status":{"type":"string"}},"required":["claim","evidence","status"]}},"live_counts":{"type":"object"},"artifacts":{"type":"array","items":{"type":"string"}}},"required":["emem_commit","summary","top_claims","live_counts","artifacts"]}
schema_cl = {"type":"object","properties":{"poster_commit":{"type":"string"},"mismatches":{"type":"array","items":{"type":"string"}},"strongest_results":{"type":"array","items":{"type":"string"}},"objections":{"type":"array","items":{"type":"object","properties":{"objection":{"type":"string"},"answer":{"type":"string"},"kind":{"type":"string"}},"required":["objection","answer","kind"]}},"refutation_policy":{"type":"string"},"artifacts":{"type":"array","items":{"type":"string"}}},"required":["poster_commit","mismatches","strongest_results","objections","refutation_policy","artifacts"]}

